### PR TITLE
[히스] Update #16, #17, #21

### PR DESCRIPTION
**Pull request by Heeseok-Jeong**

### CODE REVIEW

**Review by changwoomon — APPROVED** [review]
빠르시네요.. 고생하셨습니다!-!

**Review by CoodingPenguin — APPROVED** [review]
수고하셨습니다!

**Comment by Heeseok-Jeong** [comment]
@bsm8734 Review and approve please.

**Review by bsm8734 — APPROVED** [review]

**Comment by bsm8734** [comment]
고생하셨습니다! 늦게 확인해서 죄송해요 🥲

**Pull request merged**
